### ISSUE TITLE
InventoryItemLite items don't show up in advanced querying

### ISSUE THREAD

**Issue by xyx0826** [joshhunt/destinyDataExplorer#28]
When querying from the console, items from `DestinyInventoryItemLiteDefinition` doesn't show up in the view.

Example:

```js
window.$DestinyInventoryItemLiteDefinition.filter(x => x.collectibleHash === 2325722862).show()
```

Returns a single item. Nothing shows up on the page.

```js
window.$DestinyInventoryItemLiteDefinition.filter(x => x.itemTypeDisplayName === "Repeatable Bounty").show()
```

Returns an `Array(43)`. Nothing shows up on the page. In comparison, the same query works on `DestinyInventoryItemDefinition`:

```js
window.$DestinyInventoryItemDefinition.filter(x => x.itemTypeDisplayName === "Repeatable Bounty").show()
```

**Comment by joshhunt** [comment]
For better or worse, this is on purpose. 

Until very recently, definitions were loaded from the SQLite .content database, which was lacking a few tables. Then I added in support for loading the missing tables from their individual JSON files. I specifically exclude DestinyInventoryItemLiteDefinition because of it's large volume of redundant data.

**Comment by xyx0826** [comment]
Understood, thanks.
